version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - REST_API_URI=localhost:3000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    environment:
      - MONGO_URI=db/store